---@meta

---@class ABP_48x48_ShopLarge_02a_C : AActor
---@field StaticMesh UStaticMeshComponent
---@field StaticMeshComponent063 UStaticMeshComponent
---@field StaticMeshComponent062 UStaticMeshComponent
---@field StaticMeshComponent061 UStaticMeshComponent
---@field StaticMeshComponent060 UStaticMeshComponent
---@field StaticMeshComponent059 UStaticMeshComponent
---@field StaticMeshComponent058 UStaticMeshComponent
---@field StaticMeshComponent057 UStaticMeshComponent
---@field StaticMeshComponent056 UStaticMeshComponent
---@field StaticMeshComponent055 UStaticMeshComponent
---@field StaticMeshComponent054 UStaticMeshComponent
---@field StaticMeshComponent053 UStaticMeshComponent
---@field StaticMeshComponent052 UStaticMeshComponent
---@field StaticMeshComponent051 UStaticMeshComponent
---@field StaticMeshComponent050 UStaticMeshComponent
---@field StaticMeshComponent049 UStaticMeshComponent
---@field StaticMeshComponent048 UStaticMeshComponent
---@field StaticMeshComponent047 UStaticMeshComponent
---@field StaticMeshComponent046 UStaticMeshComponent
---@field StaticMeshComponent045 UStaticMeshComponent
---@field StaticMeshComponent044 UStaticMeshComponent
---@field StaticMeshComponent043 UStaticMeshComponent
---@field StaticMeshComponent042 UStaticMeshComponent
---@field StaticMeshComponent041 UStaticMeshComponent
---@field StaticMeshComponent040 UStaticMeshComponent
---@field StaticMeshComponent039 UStaticMeshComponent
---@field StaticMeshComponent038 UStaticMeshComponent
---@field StaticMeshComponent010 UStaticMeshComponent
---@field StaticMeshComponent036 UStaticMeshComponent
---@field StaticMeshComponent035 UStaticMeshComponent
---@field StaticMeshComponent034 UStaticMeshComponent
---@field StaticMeshComponent033 UStaticMeshComponent
---@field StaticMeshComponent03 UStaticMeshComponent
---@field StaticMeshComponent031 UStaticMeshComponent
---@field StaticMeshComponent030 UStaticMeshComponent
---@field StaticMeshComponent029 UStaticMeshComponent
---@field StaticMeshComponent028 UStaticMeshComponent
---@field StaticMeshComponent027 UStaticMeshComponent
---@field StaticMeshComponent026 UStaticMeshComponent
---@field StaticMeshComponent025 UStaticMeshComponent
---@field StaticMeshComponent024 UStaticMeshComponent
---@field StaticMeshComponent023 UStaticMeshComponent
---@field StaticMeshComponent022 UStaticMeshComponent
---@field StaticMeshComponent021 UStaticMeshComponent
---@field StaticMeshComponent020 UStaticMeshComponent
---@field StaticMeshComponent019 UStaticMeshComponent
---@field StaticMeshComponent018 UStaticMeshComponent
---@field StaticMeshComponent017 UStaticMeshComponent
---@field StaticMeshComponent016 UStaticMeshComponent
---@field StaticMeshComponent015 UStaticMeshComponent
---@field StaticMeshComponent014 UStaticMeshComponent
---@field StaticMeshComponent013 UStaticMeshComponent
---@field StaticMeshComponent012 UStaticMeshComponent
---@field StaticMeshComponent011 UStaticMeshComponent
---@field StaticMeshComponent037 UStaticMeshComponent
---@field StaticMeshComponent07 UStaticMeshComponent
---@field StaticMeshComponent06 UStaticMeshComponent
---@field StaticMeshComponent05 UStaticMeshComponent
---@field StaticMeshComponent04 UStaticMeshComponent
---@field StaticMeshComponent08 UStaticMeshComponent
---@field StaticMeshComponent02 UStaticMeshComponent
---@field StaticMeshComponent01 UStaticMeshComponent
---@field StaticMeshComponent0 UStaticMeshComponent
---@field StaticMeshComponent032 UStaticMeshComponent
---@field StaticMeshComponent09 UStaticMeshComponent
---@field SharedRoot USceneComponent
local ABP_48x48_ShopLarge_02a_C = {}



