---@meta

---@class ABP_TownHouse_06_C : AStaticMeshActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Candle_05 UChildActorComponent
---@field SM_ChristmasDeco_Wreath_09 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_08 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_07 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_06 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_05 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_04 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_03 UStaticMeshComponent
---@field SM_ChristmasDeco_Wreath_02 UStaticMeshComponent
---@field SM_ChristmasTree_03 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_08 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_010 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_09 UStaticMeshComponent
---@field SM_Townhouse_Entrance_01 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_018 UStaticMeshComponent
---@field SM_TownHouse_Wall_08 UStaticMeshComponent
---@field SM_Pipe_014 UStaticMeshComponent
---@field SM_Pipe_013 UStaticMeshComponent
---@field SM_Pipe_012 UStaticMeshComponent
---@field SM_Pipe_011 UStaticMeshComponent
---@field SM_Pipe_010 UStaticMeshComponent
---@field SM_Pipe_09 UStaticMeshComponent
---@field SM_Pipe_08 UStaticMeshComponent
---@field SM_Pipe_07 UStaticMeshComponent
---@field SM_Pipe_06 UStaticMeshComponent
---@field SM_TownHouse_Wall_04 UStaticMeshComponent
---@field SM_TownHouse_Wall_01 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_016 UStaticMeshComponent
---@field SM_TownHouse_Wall_013 UStaticMeshComponent
---@field SM_TownHouse_Pillar_02 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B3 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B2 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B1 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B UStaticMeshComponent
---@field SM_TownHouse_Pillar_09 UStaticMeshComponent
---@field SM_TownHouse_Wall_07 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_015 UStaticMeshComponent
---@field SM_TownHouse_Pillar_08 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B7 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B6 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B5 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04_B4 UStaticMeshComponent
---@field SM_TownHouse_Pillar_06 UStaticMeshComponent
---@field SM_TownHouse_Wall_05 UStaticMeshComponent
---@field SM_TownHouse_Wall_06 UStaticMeshComponent
---@field SM_TownHouse_Chimney_04 UStaticMeshComponent
---@field SM_Pipe_05 UStaticMeshComponent
---@field SM_Pipe_04 UStaticMeshComponent
---@field SM_Pipe_03 UStaticMeshComponent
---@field WallLight_03 UChildActorComponent
---@field SM_Townhouse_Roof_06 UStaticMeshComponent
---@field SM_Townhouse_Roof_05 UStaticMeshComponent
---@field SM_Townhouse_Roof_04 UStaticMeshComponent
---@field SM_Townhouse_Roof_03 UStaticMeshComponent
---@field SM_TownHouse_Floor_04 UStaticMeshComponent
---@field SM_TownHouse_Floor_011 UStaticMeshComponent
---@field SM_TownHouse_Floor_010 UStaticMeshComponent
---@field SM_TownHouse_Floor_09 UStaticMeshComponent
---@field SM_TownHouse_Floor_08 UStaticMeshComponent
---@field SM_TownHouse_Floor_07 UStaticMeshComponent
---@field SM_TownHouse_Floor_06 UStaticMeshComponent
---@field SM_TownHouse_Floor_05 UStaticMeshComponent
---@field SM_TownHouse_Floor_02 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_06 UStaticMeshComponent
---@field SM_TownHouse_Pillar_07 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_07 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_05 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_03 UStaticMeshComponent
---@field SM_TownHouse_Pillar_04 UStaticMeshComponent
---@field SM_TownHouse_DoorWall_01 UStaticMeshComponent
---@field SM_TownHouse_Pillar_05 UStaticMeshComponent
---@field SM_TownHouse_Pillar_01 UStaticMeshComponent
---@field SM_TownHouse_Floor_03 UStaticMeshComponent
---@field SM_TownHouse_Floor_015 UStaticMeshComponent
---@field SM_TownHouse_Floor_013 UStaticMeshComponent
---@field SM_Townhouse_Door_01 UStaticMeshComponent
---@field SM_TownHouse_Floor_01 UStaticMeshComponent
---@field HouseMaterial UMaterialInstance
---@field GlassMaterial UMaterialInstance
---@field UseableDoor boolean
---@field IsTurnedOn boolean
---@field IsChristmas boolean
local ABP_TownHouse_06_C = {}

function ABP_TownHouse_06_C:TurnMaterial() end
ABP_TownHouse_06_C['Town House'] = function(self, ) end
function ABP_TownHouse_06_C:UserConstructionScript() end
---@param DeltaSeconds float
function ABP_TownHouse_06_C:ReceiveTick(DeltaSeconds) end
---@param EntryPoint int32
function ABP_TownHouse_06_C:ExecuteUbergraph_BP_TownHouse_06(EntryPoint) end


