---@meta

---@class ATownHouse_01_C : AMTBuilding
---@field UberGraphFrame FPointerToUberGraphFrame
---@field MTInteractable UMTInteractableComponent
---@field BuildingInteraction UStaticMeshComponent
---@field ChildActor6 UChildActorComponent
---@field ChildActor4 UChildActorComponent
---@field ChildActor5 UChildActorComponent
---@field ChildActor3 UChildActorComponent
---@field ChildActor2 UChildActorComponent
---@field ChildActor1 UChildActorComponent
---@field ChildActor UChildActorComponent
---@field SM_TownWareHouse_01 UStaticMeshComponent
---@field SM_TownHouse_Floor_04 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_03 UStaticMeshComponent
---@field SM_TownHouse_Floor_01 UStaticMeshComponent
---@field SM_Townhouse_OutFence_05 UStaticMeshComponent
---@field SM_Townhouse_Roof_04 UStaticMeshComponent
---@field Scene USceneComponent
---@field SM_TownHouse_OutFence_013 UStaticMeshComponent
---@field SM_TownHouse_OutFence_012 UStaticMeshComponent
---@field SM_Townhouse_OutStairs_04 UStaticMeshComponent
---@field SM_Townhouse_OutStairs_03 UStaticMeshComponent
---@field SM_Bld_Floor_Ceiling_Wood_02 UStaticMeshComponent
---@field SM_Bld_Floor_Ceiling_Wood_01 UStaticMeshComponent
---@field SM_TownHouse_Chimney_02 UStaticMeshComponent
---@field SM_TownHouse_Chimney_04 UStaticMeshComponent
---@field SM_TownHouse_Chimney_03 UStaticMeshComponent
---@field WallLight_06 UChildActorComponent
---@field WallLight_04 UChildActorComponent
---@field WallLight_03 UChildActorComponent
---@field WallLight_05 UChildActorComponent
---@field SM_Townhouse_OutStairs_02 UStaticMeshComponent
---@field SM_Townhouse_Roof_05 UStaticMeshComponent
---@field SM_Townhouse_Roof_02 UStaticMeshComponent
---@field SM_Townhouse_Roof_03 UStaticMeshComponent
---@field SM_Townhouse_Roof_07 UStaticMeshComponent
---@field SM_Townhouse_Roof_06 UStaticMeshComponent
---@field SM_TownHouse_Floor_03 UStaticMeshComponent
---@field SM_TownHouse_Floor_020 UStaticMeshComponent
---@field SM_TownHouse_Floor_016 UStaticMeshComponent
---@field SM_TownHouse_Floor_015 UStaticMeshComponent
---@field SM_TownHouse_Floor_013 UStaticMeshComponent
---@field SM_TownHouse_DoorWall_01 UStaticMeshComponent
---@field SM_TownHouse_Pillar_06 UStaticMeshComponent
---@field SM_TownHouse_Wall_07 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_06 UStaticMeshComponent
---@field SM_TownHouse_Wall_05 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_05 UStaticMeshComponent
---@field SM_TownHouse_Wall_06 UStaticMeshComponent
---@field SM_TownHouse_Wall_01 UStaticMeshComponent
---@field SM_TownHouse_Pillar_03 UStaticMeshComponent
---@field SM_TownHouse_Pillar_04 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_02 UStaticMeshComponent
---@field SM_TownHouse_Pillar_02 UStaticMeshComponent
---@field SM_TownHouse_Wall_02 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_01 UStaticMeshComponent
---@field SM_TownHouse_Wall_03 UStaticMeshComponent
---@field SM_TownHouse_Wall_04 UStaticMeshComponent
---@field SM_TownHouse_Pillar_05 UStaticMeshComponent
---@field SM_TownHouse_Pillar_01 UStaticMeshComponent
---@field SM_TownHouse_WindowWall_04 UStaticMeshComponent
---@field SM_TownHouse_DoorWall_02 UStaticMeshComponent
---@field SM_Townhouse_OutFence_011 UStaticMeshComponent
---@field SM_Townhouse_OutFence_010 UStaticMeshComponent
---@field SM_Townhouse_OutFence_09 UStaticMeshComponent
---@field SM_Townhouse_OutFence_03 UStaticMeshComponent
---@field SM_TownHouse_OutFence_01 UStaticMeshComponent
---@field SM_Townhouse_OutStairs_01 UStaticMeshComponent
---@field SM_TownHouse_OutFence_02 UStaticMeshComponent
---@field SM_Townhouse_OutFence_04 UStaticMeshComponent
---@field SM_Townhouse_OutFence_06 UStaticMeshComponent
---@field SM_Townhouse_OutFence_08 UStaticMeshComponent
---@field SM_Townhouse_OutFence_07 UStaticMeshComponent
---@field SM_TownHouse_Floor_09 UStaticMeshComponent
---@field HouseMaterial UMaterialInstance
---@field GlassMaterial UMaterialInstance
---@field UseableDoor boolean
---@field IsTurnedOn boolean
local ATownHouse_01_C = {}

function ATownHouse_01_C:TurnMaterial() end
ATownHouse_01_C['Town House'] = function(self, ) end
function ATownHouse_01_C:UserConstructionScript() end
---@param DeltaSeconds float
function ATownHouse_01_C:ReceiveTick(DeltaSeconds) end
---@param EntryPoint int32
function ATownHouse_01_C:ExecuteUbergraph_TownHouse_01(EntryPoint) end


