#!/usr/bin/env python3
"""
Fix missing debug directory in PE files generated by lld-link cross-compilation.

lld-link with /DEBUG:FULL creates a PDB and embeds the RSDS CodeView record in
the binary, but fails to write the IMAGE_DEBUG_DIRECTORY entry that points to it.
Without this directory, crash dumps cannot auto-match PDBs.

This script patches the PE file to add the missing debug directory entry.
"""

import struct
import sys
import os


def find_rsdS_record(data):
    """Find the RSDS CodeView record in the PE file."""
    offset = 0
    while True:
        offset = data.find(b'RSDS', offset)
        if offset == -1:
            return None
        # Verify it looks like a valid RSDS (should have reasonable PDB path after it)
        if offset + 24 < len(data):
            age = struct.unpack('<I', data[offset + 20:offset + 24])[0]
            if age > 0 and age < 1000:  # Reasonable age value
                return offset
        offset += 1
    return None


def get_pe_info(data):
    """Parse basic PE header info."""
    pe_offset = struct.unpack('<I', data[0x3c:0x40])[0]
    
    # COFF header
    num_sections = struct.unpack('<H', data[pe_offset + 6:pe_offset + 8])[0]
    size_opt = struct.unpack('<H', data[pe_offset + 20:pe_offset + 22])[0]
    
    # Optional header magic
    magic = struct.unpack('<H', data[pe_offset + 24:pe_offset + 26])[0]
    is_64 = (magic == 0x20b)
    
    # Data directories
    dd_offset = pe_offset + 24 + (144 if is_64 else 96)
    
    # Debug directory (entry 6)
    debug_rva = struct.unpack('<I', data[dd_offset + 48:dd_offset + 52])[0]
    debug_size = struct.unpack('<I', data[dd_offset + 52:dd_offset + 56])[0]
    
    return {
        'pe_offset': pe_offset,
        'num_sections': num_sections,
        'size_opt': size_opt,
        'is_64': is_64,
        'dd_offset': dd_offset,
        'debug_rva': debug_rva,
        'debug_size': debug_size,
    }


def rva_to_file_offset(data, rva, pe_info):
    """Convert RVA to file offset by looking up the section table."""
    pe_offset = pe_info['pe_offset']
    size_opt = pe_info['size_opt']
    num_sections = pe_info['num_sections']
    
    section_table = pe_offset + 24 + size_opt
    
    for s in range(num_sections):
        off = section_table + s * 40
        name = data[off:off + 8].rstrip(b'\x00').decode('ascii', errors='replace')
        virt_size = struct.unpack('<I', data[off + 8:off + 12])[0]
        virt_addr = struct.unpack('<I', data[off + 12:off + 16])[0]
        raw_size = struct.unpack('<I', data[off + 16:off + 20])[0]
        raw_addr = struct.unpack('<I', data[off + 20:off + 24])[0]
        
        if virt_addr <= rva < virt_addr + max(virt_size, raw_size):
            return raw_addr + (rva - virt_addr)
    
    return None


def file_offset_to_rva(data, file_offset, pe_info):
    """Convert file offset to RVA by looking up the section table."""
    pe_offset = pe_info['pe_offset']
    size_opt = pe_info['size_opt']
    num_sections = pe_info['num_sections']
    
    section_table = pe_offset + 24 + size_opt
    
    for s in range(num_sections):
        off = section_table + s * 40
        virt_size = struct.unpack('<I', data[off + 8:off + 12])[0]
        virt_addr = struct.unpack('<I', data[off + 12:off + 16])[0]
        raw_size = struct.unpack('<I', data[off + 16:off + 20])[0]
        raw_addr = struct.unpack('<I', data[off + 20:off + 24])[0]
        
        if raw_addr <= file_offset < raw_addr + max(raw_size, virt_size):
            return virt_addr + (file_offset - raw_addr)
    
    return None


def patch_pe_debug_dir(pe_path):
    with open(pe_path, 'r+b') as f:
        data = bytearray(f.read())
    
    # Find RSDS record
    rsds_offset = find_rsdS_record(data)
    if rsds_offset is None:
        print(f"No RSDS record found in {pe_path}")
        return False
    
    pe_info = get_pe_info(data)
    
    if pe_info['debug_rva'] == 0 or pe_info['debug_size'] == 0:
        print(f"No debug directory allocated in {pe_path}")
        return False
    
    # Calculate RVA of RSDS record
    rsds_rva = file_offset_to_rva(data, rsds_offset, pe_info)
    if rsds_rva is None:
        print(f"Could not map RSDS file offset {rsds_offset:#x} to RVA")
        return False
    
    # Find the RSDS record size (includes GUID + age + null-terminated path)
    # Find null terminator of PDB path
    path_start = rsds_offset + 24
    path_end = data.find(b'\x00', path_start)
    if path_end == -1:
        path_end = len(data)
    rsds_size = path_end - rsds_offset + 1  # Include null terminator
    
    # Find debug directory file offset
    debug_offset = rva_to_file_offset(data, pe_info['debug_rva'], pe_info)
    if debug_offset is None:
        print(f"Could not map debug dir RVA {pe_info['debug_rva']:#x} to file offset")
        return False
    
    # Verify debug directory is empty (all zeros or has invalid entries)
    debug_data = data[debug_offset:debug_offset + pe_info['debug_size']]
    
    # Check if already patched
    for i in range(0, len(debug_data), 28):
        entry = debug_data[i:i + 28]
        if len(entry) < 28:
            break
        dtype = struct.unpack('<I', entry[12:16])[0]
        if dtype == 2:
            print(f"{pe_path}: debug directory already contains CODEVIEW entry, skipping")
            return True
    
    # Create IMAGE_DEBUG_DIRECTORY entry for CODEVIEW
    entry = struct.pack('<IIHHIIII',
        0,              # Characteristics
        0,              # TimeDateStamp
        0,              # MajorVersion
        0,              # MinorVersion
        2,              # Type = IMAGE_DEBUG_TYPE_CODEVIEW
        rsds_size,      # SizeOfData
        rsds_rva,       # AddressOfRawData (RVA)
        rsds_offset,    # PointerToRawData (file offset)
    )
    
    # Write entry at the beginning of the debug directory
    data[debug_offset:debug_offset + 28] = entry
    
    with open(pe_path, 'wb') as f:
        f.write(data)
    
    print(f"Patched {pe_path}:")
    print(f"  RSDS at file offset {rsds_offset:#x} (RVA {rsds_rva:#x})")
    print(f"  Debug directory at file offset {debug_offset:#x} (RVA {pe_info['debug_rva']:#x})")
    print(f"  Added CODEVIEW entry pointing to RSDS (size={rsds_size})")
    return True


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <pe_file.dll> [pe_file2.dll ...]")
        sys.exit(1)
    
    ok = True
    for path in sys.argv[1:]:
        if not os.path.exists(path):
            print(f"File not found: {path}")
            ok = False
            continue
        if not patch_pe_debug_dir(path):
            ok = False
    
    sys.exit(0 if ok else 1)
